version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/461-Phase2

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_program.sh
      timeout: 300
      runas: ec2-user
  
  ApplicationStop:
  - location: scripts/stop_program.sh
    timeout: 300
    runas: ec2-user